Testing suite for gaussian.py and samba_models by extension
danOSU/Taweret pull request #23
Opened 2023-04-07 14:34 UTC by asemposki

Here is the testing suite I wrote with five test functions, each of which tests the evaluation and predictions of my BMM code when given a specific SAMBA model with a truncation at third order in both models. This may need to be altered later, but for now it can compare to the data in samba_results.txt to check itself. 

I have one warning that I have not figured out yet, but other than that all tests are passing.

2023-04-14 16:56 UTC, danOSU requested changes

2023-04-14 16:56 UTC, danOSU commented on test/test_gaussian.py
> +def test_models():
@asemposki can you see this?

2023-04-14 17:08 UTC, asemposki commented on test/test_gaussian.py
> +def test_mixing():
test_mixing() tests that the mixed model is yielding something back that is not None, but it is not testing that the results of the mixed model are equal to that of SAMBA's mixing. I can add to the samba_results.txt file the mixed model and use that here.

2023-04-14 17:29 UTC, asemposki commented on test/test_gaussian.py
> +    assert np.array_equal(weights, mixed.var_weights), "weights are incorrect"
No, the weights come from the mixing. They are my precision values from the way that I perform multivariate mixing, so they do not come from the input models alone. Hence they are part of the mixing class for me and they are generated while mixing, so the evaluate_weights() function returns their values from when mixing has been performed.

2023-04-19 14:51 UTC, asemposki commented
Reopening the PR.

2023-04-19 21:45 UTC, merged